version: '3'
services:
  web:
    # image: my_videolibrary_web:latest
    build: .
    # command: python -m flask run
    ports:
      - "5000:5000"
    # volumes:
    #   - .:/todo
    links:
      - my_mongodb
    depends_on:
      - my_mongodb 
    environment:
      - MONGO_DB_URL=my_mongodb
      - MONGO_DB_PORT=27017

  my_mongodb:
    image: mongo:4.1.4-xenial
    container_name: "my_mongodb"
    volumes:
      - mongodb_data:/data/db
    # - mongo-config:/data/configdb
    ports:
      - 27017:27017
    # command: mongod  --logpath=/dev/null 

    environment:
      - MONGO_DATA_DIR=/data/db
  

volumes:
   mongodb_data:
   # https://github.com/cytopia/devilbox/issues/175
  #  https://forums.docker.com/t/trying-to-get-postgres-to-work-on-persistent-windows-mount-two-issues/12456/5?u=friism
  