version: '3'
services:
  my_mongoDB:
    image: mongo:4.1.4-xenial
    container_name: "mongodb"
    volumes:
      - mongodb_data:/data/db
    # - mongo-config:/data/configdb
    ports:
      - 27017:27017
    # command: mongod  --logpath=/dev/null 

    environment:
      - MONGO_DATA_DIR=/data/db 

volumes:
   mongodb_data:
   # https://github.com/cytopia/devilbox/issues/175
  #  https://forums.docker.com/t/trying-to-get-postgres-to-work-on-persistent-windows-mount-two-issues/12456/5?u=friism
  